language: node_js

node_js:
  - 14.5.0

script:
  - npm run test -- --maxWorkers=4

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

services:
  - xvfb

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules